version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: kaushalya@2017
      MYSQL_DATABASE: demodb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask:
    build: .
    image: my-flask-app:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=kaushalya@2017
      - DB_NAME=demodb
    depends_on:
      - db

volumes:
  db_data: