version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: kaushalya@2017
      MYSQL_DATABASE: dockerdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql      
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build: .
    image: mycrudsqlapp:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=kaushalya@2017
      - DB_NAME=dockerdb
    depends_on:
      - db

volumes:
  db_data: